spring:
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

management:
  health:
    mail:
      enabled: true

app:
  monerium:
    client-id: ${MONERIUM_CLIENT_ID}
    client-secret: ${MONERIUM_CLIENT_SECRET}
    base-url: ${MONERIUM_BASE_URL}
    redirect-uri: ${MONERIUM_REDIRECT_URI}
